### ISSUE TITLE
feat: GitLab

### ISSUE THREAD

**Issue by apricote** [apricote/releaser-pleaser#4]
We currently only support repositories on GitHub, I would like to see support for GitLabs APIs and GitLab CI.

### API (Forge)

This was implemented in these pull requests:

- #49 
- #51 
- #53 
- #54 

### GitLab CI/CD

This is a bit more complicated. GitLab CI/CD has multiple drawbacks against GitHub Actions:

- CI/CD pipelines can only be started on repository events, like pushes. We can not start a new job whenever the description is changed
- The default API Token that as available in the pipeline is severly restricted. The only way around this is with a (project/group/personal) access token with the permissions `api` and `write_repository`.

This is currently in progress:

- #55 

I have also thought about adding a Webhook server that one can deploy to manually create CI jobs when the description is updated.

**Comment by jooola** [comment]
To run this tool in GitLab CI pipelines, we must be able to shell into the container image. The default base image from ko seem to not provide a shell. We might need to add a shell binary or swap the base image with something more flexible.

**Comment by apricote** [comment]
I think with [Steps](https://docs.gitlab.com/ee/ci/steps/) we could keep publishing a `ko`-built image and use it on GitLab. Downside is that Steps are marked as _experimental_ right now.

Alternatively we can switch the ko base image from `cgr.dev/chainguard/static` to `cgr.dev/chainguard/busybox` (`ash`) or `cgr.dev/chainguard/bash`.

**Comment by apricote** [comment]
First usable version of this was published in [v0.4.0-beta.1](https://github.com/apricote/releaser-pleaser/releases/tag/v0.4.0-beta.1). Still working on documentation before creating a proper release

**Comment by apricote** [comment]
Docs are now available and this will be released in 0.4.0.
