### ISSUE TITLE
Missing commit from changelog after commit parsing failed

### ISSUE THREAD

**Issue by jooola** [apricote/releaser-pleaser#99]
A commit is missing from the CHANGELOG.md:

Commit: https://gitlab.com/hetznercloud/fleeting-plugin-hetzner/-/commit/92861c539ef6b6cfa54ce360f7b6168ef7b86798
Release notes: https://gitlab.com/hetznercloud/fleeting-plugin-hetzner/-/releases/v0.6.0
Changelog: https://gitlab.com/hetznercloud/fleeting-plugin-hetzner/-/blob/main/CHANGELOG.md?ref_type=heads
Releaser pleaser logs: https://gitlab.com/hetznercloud/fleeting-plugin-hetzner/-/jobs/8274682807#L62

Commit message:
```
feat: allow attaching a volume to an instance (hetznercloud/fleeting-plugin-hetzner!144)
    
Fixes #15
    
Depends on !143
```

**Comment by apricote** [comment]
Copying from #100:

Looking at the conventional commits spec your example commit message is on the line of illegality.

```
feat: some thing (hz/fl!144)

Fixes #15             <-- Intepreted as a footer/trailer
                      
Depends on !143       <-- Should also be a footer/trailer, but does not follow the expected format
```

Spec: https://www.conventionalcommits.org/en/v1.0.0/#specification

> One or more footers MAY be provided one blank line after the body. Each footer MUST consist of a word token, followed by either a : or # separator, followed by a string value (this is inspired by the [git trailer convention](https://git-scm.com/docs/git-interpret-trailers)).

Anyway, this is a footgun that should be removed/fixed.

Tried to implement a fix for this in `github.com/leodido/go-conventionalcommits` myself but did not get anywhere. I opened https://github.com/leodido/go-conventionalcommits/issues/38 instead.

For now I have a quick fix that will at least make sure that no commits are ignored. PR incoming.
